# Generated by Django 4.2.2 on 2023-08-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveEdit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
