# Generated by Django 4.2.4 on 2023-08-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveEdit', '0002_document_name'),
        ('liveEdit', '0002_document_name_alter_document_content'),
    ]

    operations = [
    ]
