# Generated by Django 4.2.2 on 2023-08-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveEdit', '0002_document_name_alter_document_content'),
        ('videoCall', '0004_alter_roommember_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='doc',
            field=models.ManyToManyField(related_name='group', to='liveEdit.document'),
        ),
    ]
