<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-08-16 08:46
=======
# Generated by Django 4.2.4 on 2023-08-14 16:25
>>>>>>> 193076cf095e1cf2b4ad889d7eb75c93e4744e43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('liveEdit', '0002_document_name_alter_document_content'),
=======
        ('liveEdit', '0001_initial'),
>>>>>>> 193076cf095e1cf2b4ad889d7eb75c93e4744e43
        ('videoCall', '0004_alter_roommember_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='doc',
            field=models.ManyToManyField(related_name='group', to='liveEdit.document'),
        ),
    ]
