# Generated by Django 4.2.4 on 2023-08-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveEdit', '0001_initial'),
        ('videoCall', '0004_alter_roommember_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='doc',
            field=models.ManyToManyField(related_name='group', to='liveEdit.document'),
        ),
    ]
