# Generated by Django 4.2.4 on 2023-08-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveEdit', '0003_merge_20230816_1843'),
        ('videoCall', '0005_group_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='doc',
            field=models.ManyToManyField(related_name='groups', to='liveEdit.document'),
        ),
    ]
