# Generated by Django 4.2.4 on 2023-08-23 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoCall', '0009_profile_doc_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='doc_created',
        ),
    ]
