# Generated by Django 4.2.4 on 2023-08-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoCall', '0011_recording_group_records_profile_recordings'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
