# Generated by Django 4.2.4 on 2023-08-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoCall', '0012_recording_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='sid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
