# Generated by Django 4.2.4 on 2023-08-25 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoCall', '0013_recording_sid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recording',
            options={'ordering': ['-created']},
        ),
    ]
