# Generated by Django 4.2.4 on 2023-08-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoCall', '0014_alter_recording_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='uid',
            field=models.CharField(default='1', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recording',
            name='sid',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
