# Generated by Django 4.2.4 on 2023-08-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoCall', '0015_recording_uid_alter_recording_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='url',
        ),
    ]
