# Generated by Django 4.2.4 on 2023-08-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoCall', '0016_remove_recording_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.ImageField(default='group.jpg', upload_to='icon/'),
            preserve_default=False,
        ),
    ]
