# Generated by Django 4.2.4 on 2023-08-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoCall', '0020_alter_group_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.ImageField(null=True, upload_to='icon'),
        ),
    ]
