# Generated by Django 4.2.4 on 2023-08-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoCall', '0021_alter_group_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='group',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
