# Generated by Django 4.2.4 on 2023-08-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoCall', '0022_alter_group_options_group_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='group',
            name='updated',
        ),
    ]
