# Generated by Django 4.2.4 on 2023-08-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoCall', '0024_notification_profile_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created']},
        ),
    ]
