# Generated by Django 4.2.4 on 2023-08-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoCall', '0026_remove_profile_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='profiles',
            field=models.ManyToManyField(related_name='all_notifications', to='videoCall.profile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='seen',
            field=models.ManyToManyField(related_name='seen_notifications', to='videoCall.profile'),
        ),
    ]
